import express from 'express';
import path from 'path';

const app = express();

// Serve static files from the "dist" directory (generated by Vite)
app.use(express.static(path.join(process.cwd(), 'dist')));

// Handle all other routes by serving the index.html file
app.get('*', (req, res) => {
  res.sendFile(path.join(process.cwd(), 'dist', 'index.html'));
});

// Start the server
const PORT = process.env.PORT || 3000; // Changed from 5000 to 3000
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});